{% set name = "emdfile" %}
{% set version = "0.0.14" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/emdfile-{{ version }}.tar.gz
  sha256: 4730f39fd19bc8d8d410193ec7ebc89a839a01f39fa3e794051f5507530b60bf

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - hatchling
    - pip
  run:
    - python >=3.8
    - h5py >=3.2.0
    - tqdm >=4.46.1
    - numpy
    - scipy

test:
  imports:
    - emdfile
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/py4dstem/emdfile
  summary: interfaces with EMD 1.0 files
  description: |
    EMD (Electron Microscopy Dataset) 1.0 is an HDF5 based file format 
    which is designed to carry arbitrary data and metadata. emdfile is a
    Python package defining write and read functions and a set of classes 
    which together interface between EMD 1.0 files and Python runtime 
    objects. The classes are designed to quickly build, save to, and read 
    from filetree-like representations of data and metadata, and is built
    on HDF5+h5py.
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  doc_url: https://emdatasets.com/format/
  dev_url: https://github.com/py4dstem/emdfile

extra:
  recipe-maintainers:
    - jan-janssen
